"""initial_21_tables

Revision ID: 61a4199a88b0
Revises: 
Create Date: 2026-05-26 12:33:32.056501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a4199a88b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文章ID'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: getting_started/features/faq/troubleshooting'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容(Markdown)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布'),
    sa.Column('is_faq', sa.Boolean(), nullable=False, comment='是否为FAQ'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_articles_category'), 'help_articles', ['category'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='权限ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限标识: resource:create/note:delete/...'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块: auth/user/course/resource/...'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='租户标识（URL友好）'),
    sa.Column('schema_name', sa.String(length=50), nullable=False, comment='数据库Schema名称'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='绑定域名'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='Logo URL'),
    sa.Column('plan', sa.String(length=20), nullable=False, comment='套餐: free/basic/premium/enterprise'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='最大用户数'),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False, comment='最大存储空间(MB)'),
    sa.Column('settings', sa.Text(), nullable=True, comment='租户配置(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('slug'),
    schema='public'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称: student/teacher/admin/super_admin'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统内置角色'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='场景ID'),
    sa.Column('scene_type', sa.String(length=30), nullable=False, comment='场景类型: classroom/self_study/exam/discussion'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='场景名称'),
    sa.Column('name_en', sa.String(length=50), nullable=False, comment='场景英文名'),
    sa.Column('icon', sa.String(length=50), nullable=False, comment='图标标识'),
    sa.Column('primary_color', sa.String(length=7), nullable=False, comment='主题色(Hex)'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景描述'),
    sa.Column('layout_config', sa.Text(), nullable=True, comment='布局配置(JSON)'),
    sa.Column('feature_flags', sa.Text(), nullable=True, comment='功能开关(JSON)'),
    sa.Column('default_widgets', sa.Text(), nullable=True, comment='默认组件列表(JSON)'),
    sa.Column('ai_prompt_template', sa.Text(), nullable=True, comment='AI提示词模板'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_type')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='租户ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: student/teacher/admin/super_admin'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='年级'),
    sa.Column('school', sa.String(length=100), nullable=True, comment='学校'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('preferences', sa.Text(), nullable=True, comment='用户偏好(JSON)'),
    sa.Column('default_scene', sa.String(length=20), nullable=False, comment='默认场景'),
    sa.Column('locale', sa.String(length=10), nullable=False, comment='语言偏好'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='时区'),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False, comment='是否完成引导'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录IP'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型: create/read/update/delete/login/export'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型: user/course/note/resource/...'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='资源ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情(JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='请求ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('buddies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学伴ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='学伴名称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('personality', sa.String(length=30), nullable=False, comment='人设: encouraging/strict/humorous/gentle'),
    sa.Column('tone', sa.String(length=30), nullable=False, comment='语气: friendly/formal/casual'),
    sa.Column('interaction_mode', sa.String(length=30), nullable=False, comment='互动模式: proactive/passive/balanced'),
    sa.Column('mood', sa.String(length=20), nullable=False, comment='心情: happy/excited/thinking/concerned'),
    sa.Column('mood_score', sa.Float(), nullable=False, comment='心情分数(0-100)'),
    sa.Column('experience_points', sa.Integer(), nullable=False, comment='经验值'),
    sa.Column('level', sa.Integer(), nullable=False, comment='等级'),
    sa.Column('custom_prompt', sa.Text(), nullable=True, comment='自定义提示词'),
    sa.Column('settings', sa.Text(), nullable=True, comment='学伴配置(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_buddies_tenant_id'), 'buddies', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='课程ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='课程名称'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='课程编码'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科: math/physics/chemistry/...'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='年级'),
    sa.Column('semester', sa.String(length=20), nullable=False, comment='学期: 2024-spring'),
    sa.Column('description', sa.Text(), nullable=True, comment='课程描述'),
    sa.Column('cover_url', sa.String(length=500), nullable=True, comment='封面URL'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师用户ID'),
    sa.Column('graph_id', sa.Integer(), nullable=True, comment='关联知识图谱ID'),
    sa.Column('settings', sa.Text(), nullable=True, comment='课程配置(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='设置ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('system_enabled', sa.Boolean(), nullable=False, comment='系统通知'),
    sa.Column('course_enabled', sa.Boolean(), nullable=False, comment='课程通知'),
    sa.Column('assignment_enabled', sa.Boolean(), nullable=False, comment='作业通知'),
    sa.Column('social_enabled', sa.Boolean(), nullable=False, comment='社交通知'),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False, comment='AI通知'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False, comment='邮件推送'),
    sa.Column('push_enabled', sa.Boolean(), nullable=False, comment='推送通知'),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True, comment='免打扰开始时间 HH:MM'),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True, comment='免打扰结束时间 HH:MM'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='通知ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收用户ID'),
    sa.Column('notification_type', sa.String(length=30), nullable=False, comment='通知类型: system/course/assignment/social/ai'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='关联链接'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送者用户ID'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='元数据(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('scope', sa.String(length=100), nullable=True, comment='作用域: global/course:{id}/tenant:{id}'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_scene_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='偏好ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('scene_type', sa.String(length=30), nullable=False, comment='场景类型'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前场景'),
    sa.Column('custom_config', sa.Text(), nullable=True, comment='自定义配置(JSON)'),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False, comment='最后访问时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scene_preferences_user_id'), 'user_scene_preferences', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('agent_type', sa.String(length=30), nullable=False, comment='智能体类型: tutor/study_buddy/examiner/assistant'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题'),
    sa.Column('scene_type', sa.String(length=30), nullable=True, comment='场景类型'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='关联课程ID'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='模型名称'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('context', sa.Text(), nullable=True, comment='会话上下文(JSON)'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数量'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总Token消耗'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否归档'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_agent_type'), 'agent_sessions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_sessions_tenant_id'), 'agent_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='课堂ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='课堂主题'),
    sa.Column('description', sa.Text(), nullable=True, comment='课堂描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: scheduled/active/ended'),
    sa.Column('access_code', sa.String(length=10), nullable=True, comment='加入码'),
    sa.Column('max_participants', sa.Integer(), nullable=False, comment='最大参与人数'),
    sa.Column('participant_count', sa.Integer(), nullable=False, comment='当前参与人数'),
    sa.Column('settings', sa.Text(), nullable=True, comment='课堂配置(JSON)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code')
    )
    op.create_index(op.f('ix_classrooms_course_id'), 'classrooms', ['course_id'], unique=False)
    op.create_index(op.f('ix_classrooms_status'), 'classrooms', ['status'], unique=False)
    op.create_index(op.f('ix_classrooms_tenant_id'), 'classrooms', ['tenant_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='选课ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='学生用户ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: student/assistant'),
    sa.Column('progress', sa.Float(), nullable=False, comment='学习进度(0-100)'),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False, comment='选课时间'),
    sa.Column('dropped_at', sa.DateTime(), nullable=True, comment='退课时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='诊断ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程ID'),
    sa.Column('diagnosis_type', sa.String(length=30), nullable=False, comment='诊断类型: knowledge/comprehensive/unit'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='诊断标题'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/in_progress/completed'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='总题数'),
    sa.Column('correct_count', sa.Integer(), nullable=False, comment='正确题数'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='用时(秒)'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='知识弱点(JSON)'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='知识强项(JSON)'),
    sa.Column('recommendations', sa.Text(), nullable=True, comment='学习建议(JSON)'),
    sa.Column('report_url', sa.String(length=500), nullable=True, comment='报告文件URL'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_tenant_id'), 'diagnoses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_user_id'), 'diagnoses', ['user_id'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='教案ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='课程ID'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='教案标题'),
    sa.Column('objectives', sa.Text(), nullable=True, comment='教学目标(JSON)'),
    sa.Column('content', sa.Text(), nullable=True, comment='教案内容(富文本)'),
    sa.Column('materials', sa.Text(), nullable=True, comment='教学材料(JSON)'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='时长(分钟)'),
    sa.Column('ai_generated', sa.Boolean(), nullable=False, comment='是否AI生成'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/published/archived'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_course_id'), 'lesson_plans', ['course_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_tenant_id'), 'lesson_plans', ['tenant_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='资源ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='资源标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='资源描述'),
    sa.Column('resource_type', sa.String(length=30), nullable=False, comment='资源类型: pdf/docx/pptx/video/audio/image/other'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_key', sa.String(length=500), nullable=True, comment='对象存储Key'),
    sa.Column('url', sa.String(length=1000), nullable=True, comment='访问URL'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='缩略图URL'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='关联课程ID'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传者用户ID'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='下载次数'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览次数'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签(JSON数组)'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='元数据(JSON)'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_course_id'), 'resources', ['course_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_tenant_id'), 'resources', ['tenant_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型: text/markdown/code/image'),
    sa.Column('tokens', sa.Integer(), nullable=False, comment='Token数量'),
    sa.Column('model_name', sa.String(length=50), nullable=True, comment='使用的模型'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='元数据(JSON)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父消息ID(分支对话)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_table('classroom_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='参与者ID'),
    sa.Column('classroom_id', sa.Integer(), nullable=False, comment='课堂ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: teacher/assistant/student'),
    sa.Column('hand_raised', sa.Boolean(), nullable=False, comment='是否举手'),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='加入时间'),
    sa.Column('left_at', sa.DateTime(), nullable=True, comment='离开时间'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_participants_classroom_id'), 'classroom_participants', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_participants_user_id'), 'classroom_participants', ['user_id'], unique=False)
    op.create_table('classroom_polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='投票ID'),
    sa.Column('classroom_id', sa.Integer(), nullable=False, comment='课堂ID'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='投票问题'),
    sa.Column('options', sa.Text(), nullable=False, comment='选项(JSON数组)'),
    sa.Column('poll_type', sa.String(length=20), nullable=False, comment='类型: single/multiple'),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False, comment='是否匿名'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/closed'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_polls_classroom_id'), 'classroom_polls', ['classroom_id'], unique=False)
    op.create_table('diagnosis_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='题目ID'),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False, comment='诊断ID'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='题目内容'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题型: choice/blank/essay'),
    sa.Column('options', sa.Text(), nullable=True, comment='选项(JSON)'),
    sa.Column('correct_answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('knowledge_points', sa.Text(), nullable=True, comment='关联知识点(JSON)'),
    sa.Column('difficulty', sa.String(length=10), nullable=False, comment='难度: easy/medium/hard'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_questions_diagnosis_id'), 'diagnosis_questions', ['diagnosis_id'], unique=False)
    op.create_table('flash_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='卡片ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程ID'),
    sa.Column('diagnosis_id', sa.Integer(), nullable=True, comment='关联诊断ID'),
    sa.Column('front', sa.Text(), nullable=False, comment='正面内容(问题)'),
    sa.Column('back', sa.Text(), nullable=False, comment='背面内容(答案)'),
    sa.Column('card_type', sa.String(length=20), nullable=False, comment='卡片类型: basic/cloze/reverse'),
    sa.Column('knowledge_point', sa.String(length=200), nullable=True, comment='知识点'),
    sa.Column('difficulty', sa.String(length=10), nullable=False, comment='难度: easy/medium/hard'),
    sa.Column('ai_generated', sa.Boolean(), nullable=False, comment='是否AI生成'),
    sa.Column('repetition_count', sa.Integer(), nullable=False, comment='复习次数'),
    sa.Column('ease_factor', sa.Float(), nullable=False, comment='易度因子(SM-2算法)'),
    sa.Column('interval_days', sa.Integer(), nullable=False, comment='间隔天数'),
    sa.Column('next_review_at', sa.DateTime(), nullable=True, comment='下次复习时间'),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True, comment='上次复习时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_cards_tenant_id'), 'flash_cards', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_flash_cards_user_id'), 'flash_cards', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='笔记ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='笔记标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='笔记内容(富文本/Markdown)'),
    sa.Column('content_plain', sa.Text(), nullable=True, comment='纯文本内容(用于搜索)'),
    sa.Column('note_type', sa.String(length=20), nullable=False, comment='笔记类型: personal/course/ai_generated'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='关联课程ID'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='关联资源ID'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所有者用户ID'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签(JSON数组)'),
    sa.Column('ai_enhanced', sa.Boolean(), nullable=False, comment='是否经过AI增强'),
    sa.Column('share_code', sa.String(length=50), nullable=True, comment='分享码'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_code')
    )
    op.create_index(op.f('ix_notes_course_id'), 'notes', ['course_id'], unique=False)
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notes_tenant_id'), 'notes', ['tenant_id'], unique=False)
    op.create_table('resource_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('resource_id', sa.Integer(), nullable=False, comment='资源ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_favorites_resource_id'), 'resource_favorites', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_favorites_user_id'), 'resource_favorites', ['user_id'], unique=False)
    op.create_table('classroom_poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='投票记录ID'),
    sa.Column('poll_id', sa.Integer(), nullable=False, comment='投票ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('selected_options', sa.Text(), nullable=False, comment='选中的选项(JSON数组)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='投票时间'),
    sa.ForeignKeyConstraint(['poll_id'], ['classroom_polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_poll_votes_poll_id'), 'classroom_poll_votes', ['poll_id'], unique=False)
    op.create_table('note_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='版本ID'),
    sa.Column('note_id', sa.Integer(), nullable=False, comment='笔记ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='版本标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='版本内容'),
    sa.Column('change_summary', sa.String(length=500), nullable=True, comment='变更摘要'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_versions_note_id'), 'note_versions', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_versions_note_id'), table_name='note_versions')
    op.drop_table('note_versions')
    op.drop_index(op.f('ix_classroom_poll_votes_poll_id'), table_name='classroom_poll_votes')
    op.drop_table('classroom_poll_votes')
    op.drop_index(op.f('ix_resource_favorites_user_id'), table_name='resource_favorites')
    op.drop_index(op.f('ix_resource_favorites_resource_id'), table_name='resource_favorites')
    op.drop_table('resource_favorites')
    op.drop_index(op.f('ix_notes_tenant_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_course_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_flash_cards_user_id'), table_name='flash_cards')
    op.drop_index(op.f('ix_flash_cards_tenant_id'), table_name='flash_cards')
    op.drop_table('flash_cards')
    op.drop_index(op.f('ix_diagnosis_questions_diagnosis_id'), table_name='diagnosis_questions')
    op.drop_table('diagnosis_questions')
    op.drop_index(op.f('ix_classroom_polls_classroom_id'), table_name='classroom_polls')
    op.drop_table('classroom_polls')
    op.drop_index(op.f('ix_classroom_participants_user_id'), table_name='classroom_participants')
    op.drop_index(op.f('ix_classroom_participants_classroom_id'), table_name='classroom_participants')
    op.drop_table('classroom_participants')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_resources_tenant_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_lesson_plans_tenant_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_course_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_diagnoses_user_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_tenant_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_classrooms_tenant_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_status'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_course_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_tenant_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_agent_type'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_user_scene_preferences_user_id'), table_name='user_scene_preferences')
    op.drop_table('user_scene_preferences')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_buddies_tenant_id'), table_name='buddies')
    op.drop_table('buddies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('scenes')
    op.drop_table('roles')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_help_articles_category'), table_name='help_articles')
    op.drop_table('help_articles')
    # ### end Alembic commands ###
